"""
Shared factory_boy model factories for all tests.

Use these instead of raw model.objects.create() calls so that:
  - Test data is realistic and consistent
  - Default values are always valid
  - Relationships are automatically wired
"""

import factory
from factory.django import DjangoModelFactory

from apps.tenants.models import (
    Organization,
    OrganizationInvitation,
    OrganizationMembership,
    RoleEnum,
)
from apps.users.models import User


class UserFactory(DjangoModelFactory):
    class Meta:
        model = User
        django_get_or_create = ("email",)

    email = factory.Sequence(lambda n: f"user{n}@example.com")
    full_name = factory.Faker("name")
    is_verified = True
    is_active = True

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        manager = cls._get_manager(model_class)
        return manager.create_user(*args, **kwargs)


class OrganizationFactory(DjangoModelFactory):
    class Meta:
        model = Organization

    name = factory.Sequence(lambda n: f"Test Org {n}")
    slug = factory.LazyAttribute(lambda o: o.name.lower().replace(" ", "-"))
    # billing_plan is intentionally None by default — test orgs start unsubscribed.
    # Link a plan via SubscriptionFactory or set billing_plan explicitly if needed.
    is_active = True


class MembershipFactory(DjangoModelFactory):
    class Meta:
        model = OrganizationMembership

    organization = factory.SubFactory(OrganizationFactory)
    user = factory.SubFactory(UserFactory)
    role = RoleEnum.MEMBER


class ApiKeyFactory(DjangoModelFactory):
    """
    Creates a real ApiKey with a properly hashed secret.

    Usage:
        key, secret = ApiKeyFactory.create_with_secret(org=org, created_by=user)
    """

    class Meta:
        model = "api_keys.ApiKey"

    organization = factory.SubFactory(OrganizationFactory)
    created_by = factory.SubFactory(UserFactory)
    name = factory.Sequence(lambda n: f"Test Key {n}")
    env = "live"
    scopes = factory.LazyFunction(list)
    is_active = True

    # prefix and hashed_key are set via the _create override below
    prefix = factory.Sequence(lambda n: f"sk_live_{n:04d}")
    hashed_key = "placeholder"  # overridden in _create

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        from apps.api_keys.models import ApiKey

        # Generate a real secret and derive prefix + hash
        env = kwargs.get("env", "live")
        secret = ApiKey.generate_secret(env)
        prefix = ApiKey.derive_prefix(secret)
        hashed = ApiKey.hash_secret(secret)

        kwargs["prefix"] = prefix
        kwargs["hashed_key"] = hashed

        instance = super()._create(model_class, *args, **kwargs)
        # Stash the plaintext secret on the instance for test assertions
        instance._plaintext_secret = secret
        return instance

    @classmethod
    def create_with_secret(cls, **kwargs):
        """
        Convenience: returns (ApiKey instance, plaintext_secret) tuple.

        Example:
            key, secret = ApiKeyFactory.create_with_secret(org=org, created_by=user)
        """
        instance = cls.create(**kwargs)
        return instance, instance._plaintext_secret


class InvitationFactory(DjangoModelFactory):
    """
    Creates a PENDING OrganizationInvitation with a real token.

    Usage:
        inv = InvitationFactory(organization=org, invited_by=owner)
        inv = InvitationFactory(organization=org, email="custom@example.com", role=RoleEnum.ADMIN)
    """

    class Meta:
        model = OrganizationInvitation

    organization = factory.SubFactory(OrganizationFactory)
    email = factory.Sequence(lambda n: f"invitee{n}@example.com")
    role = RoleEnum.MEMBER
    invited_by = factory.SubFactory(UserFactory)
    # token is auto-generated by the model's save() method


# ── Billing Factories ──────────────────────────────────────────────────────────


class PlanFactory(DjangoModelFactory):
    """Creates a billing Plan. Defaults to a FREE-tier configuration."""

    class Meta:
        model = "billing.Plan"
        django_get_or_create = ("slug",)

    name = factory.Sequence(lambda n: f"Plan {n}")
    slug = factory.LazyAttribute(lambda o: o.name.lower().replace(" ", "-"))
    price_monthly = "0.00"
    limits = factory.LazyFunction(
        lambda: {
            "members_count": 5,
            "api_calls_per_month": 10_000,
            "storage_mb": 512,
        }
    )
    features = factory.LazyFunction(
        lambda: {
            "audit_logs": False,
            "feature_flags": False,
            "sso": False,
        }
    )
    is_active = True


class SubscriptionFactory(DjangoModelFactory):
    """Creates an active Subscription linking an org to a plan."""

    class Meta:
        model = "billing.Subscription"

    organization = factory.SubFactory(OrganizationFactory)
    plan = factory.SubFactory(PlanFactory)
    status = "active"
    current_period_start = factory.LazyFunction(
        lambda: __import__("django.utils.timezone", fromlist=["now"]).now()
    )
    current_period_end = factory.LazyFunction(
        lambda: __import__("django.utils.timezone", fromlist=["now"]).now()
        + __import__("datetime").timedelta(days=30)
    )


class InvoiceFactory(DjangoModelFactory):
    """Creates a PAID invoice for a subscription."""

    class Meta:
        model = "billing.Invoice"

    subscription = factory.SubFactory(SubscriptionFactory)
    amount_cents = 4900  # $49.00
    status = "paid"
    stripe_invoice_id = factory.LazyFunction(
        lambda: f"mock_inv_{__import__('uuid').uuid4().hex[:12]}"
    )
    period_start = factory.LazyFunction(
        lambda: __import__("django.utils.timezone", fromlist=["now"]).now()
    )
    period_end = factory.LazyFunction(
        lambda: __import__("django.utils.timezone", fromlist=["now"]).now()
        + __import__("datetime").timedelta(days=30)
    )
    paid_at = factory.LazyFunction(
        lambda: __import__("django.utils.timezone", fromlist=["now"]).now()
    )
