# Generated by Django 5.2.13 on 2026-04-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_organizationinvitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvitationStatus",
        ),
        migrations.RenameIndex(
            model_name="organizationinvitation",
            new_name="tenants_org_token_46a201_idx",
            old_name="tenants_org_token_inv_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationinvitation",
            new_name="tenants_org_organiz_a51597_idx",
            old_name="tenants_org_email_inv_idx",
        ),
    ]
