# Generated by Django 5.2.1 on 2026-04-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
        ("tenants", "0005_organization_billing_plan_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_prefix_c1364a_idx",
            old_name="api_keys_ap_prefix_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_ap_organiz_cd2068_idx",
            old_name="api_keys_ap_org_idx",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Optional hard expiry. Null = never expires.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="hashed_key",
            field=models.CharField(
                help_text="HMAC-SHA256 of the full secret. Never the secret itself.", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set asynchronously via Celery to avoid blocking requests.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(help_text="Human-readable label for this key.", max_length=255),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.organization",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="Plain-text prefix for fast DB lookup (e.g. 'sk_live_abc1').",
                max_length=16,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of permission scope strings this key is restricted to.",
            ),
        ),
    ]
