# Generated by Django 5.2.1 on 2026-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="featureflag",
            new_name="features_fe_key_e00778_idx",
            old_name="features_fea_key_idx",
        ),
        migrations.RenameIndex(
            model_name="featureflag",
            new_name="features_fe_is_acti_16416f_idx",
            old_name="features_fea_is_act_idx",
        ),
        migrations.RenameIndex(
            model_name="resourcesnapshot",
            new_name="features_re_resourc_9913a9_idx",
            old_name="features_res_resource_idx",
        ),
        migrations.RenameIndex(
            model_name="resourcesnapshot",
            new_name="features_re_organiz_99a79a_idx",
            old_name="features_res_org_creat_idx",
        ),
        migrations.RenameIndex(
            model_name="resourcesnapshot",
            new_name="features_re_resourc_1074c4_idx",
            old_name="features_res_resource_version_idx",
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="key",
            field=models.CharField(
                help_text="Unique identifier for the feature flag (e.g., 'feature_x', 'beta_api_v2')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata (e.g., owner, ticket link, notes)",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesnapshot",
            name="change_reason",
            field=models.CharField(
                blank=True,
                help_text="Why the change was made (e.g., 'user_edit', 'admin_action', 'system_migration')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="resourcesnapshot",
            name="resource_type",
            field=models.CharField(
                help_text="Model name (e.g., 'User', 'ApiKey', 'Organization')", max_length=100
            ),
        ),
    ]
