# Generated by Django 5.2.1 on 2026-04-17 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0005_organization_billing_plan_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=120)),
                (
                    "resource_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=120),
                ),
                ("resource_id", models.CharField(blank=True, default="", max_length=255)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["org", "-created_at"], name="auditlog_org_created_idx"),
                    models.Index(
                        fields=["actor", "-created_at"], name="auditlog_actor_created_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"], name="auditlog_resource_idx"
                    ),
                ],
            },
        ),
    ]
